[package]
name = "rsxc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-rsx"
test = false
path = "src/main.rs"

[[bin]]
name = "rsx-driver"
path = "src/driver.rs"

[dependencies]

[package.metadata.rust-analyzer]
rustc_private = true
